# Generated by Django 2.1.4 on 2018-12-21 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extendeduser',
            old_name='username',
            new_name='user',
        ),
    ]
