# Generated by Django 2.1.4 on 2018-12-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_extendeduser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='avatar',
            field=models.ImageField(null=True, upload_to='accounts/images'),
        ),
    ]
