# Generated by Django 2.1.4 on 2018-12-27 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('accounts', '0005_auto_20181222_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersIP',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ip', models.CharField(max_length=15)),
            ],
        ),
    ]
