# Generated by Django 2.1.4 on 2018-12-28 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_usersip_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersip',
            name='session',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.Session'),
        ),
    ]
